### PR TITLE
Add an ES5/IE compatible version of wrapper to distribution

### LINKED ISSUE #31: IE Support
There are now babel plugins and polyfills that can run web components on IE.
https://github.com/github/babel-plugin-transform-custom-element-classes
https://github.com/webcomponents/custom-elements

If an IE compatible version is generated and included in the distribution, it would open the door for Vue CLI to support something like [modern mode](https://cli.vuejs.org/guide/browser-compatibility.html#modern-mode) for [target web component](https://cli.vuejs.org/guide/build-targets.html#web-component).

### PR DESCRIPTION
**Pull request by ChristianMurphy**
resolves #31

### CODE REVIEW

**Comment by jgribonvald** [comment]
+1 to have a solution for IE11

**Comment by wbern** [comment]
If this means this wrapper can support IE 10, it would mean a lot.

**Comment by ChristianMurphy** [comment]
@wbern see https://github.com/vuejs/vue-web-component-wrapper/issues/31#issuecomment-427346934

**Comment by wbern** [comment]
@ChristianMurphy we are using that wrapper today for the IE legacy support it offers, but the support for templates and slots is really just not there (likely because no shadow dom) and the vue devtools extension fails to show components below the first level on pages that use it.

That's why I want to switch to this implementation.

**Comment by ChristianMurphy** [comment]
@wbern in theory this should work back to IE9, I've only done testing with IE11.

**Comment by wbern** [comment]
@ChristianMurphy in our case we need to support IE 10. I wonder if that could be targeted for this repo?

**Comment by ChuckDeng** [comment]
How would this work when making web components via the vue cli with the --target as wc? Is this based off the target browserist whether to use es6 vs es5 version of the web component wrapper?

**Comment by ChristianMurphy** [comment]
My thought is to support something like [modern mode](https://cli.vuejs.org/guide/browser-compatibility.html#modern-mode) for [target web component](https://cli.vuejs.org/guide/build-targets.html#web-component).
Where an ES6+unpolyfilled web component version and a separate ES5+polyfilled version would be generated.

**Comment by ChuckDeng** [comment]
@ChristianMurphy, the modern mode for target web component is ignored. 

`Modern mode only works with default target (app). For libraries or web components, use the browserslist config to specify target browsers.`  

Either way, when do you think this will be integrated to to the main branch? Thank you!

**Comment by ChristianMurphy** [comment]
> the modern mode for target web component is ignored

I'm aware, that's why I'm suggesting adding it :slightly_smiling_face: 

> Either way, when do you think this will be integrated to to the main branch?

If/when this will be merged is a question @yyx990803 would be able to answer.

**Comment by ChuckDeng** [comment]
@ChristianMurphy Okay, thank you.  perhaps we can add a step to transpilation step to convert the output file to es5 version for now.

**Comment by karol-f** [comment]
Guys, this PR is not getting attention from @yyx990803, either:
* he don't want to support not evergreen browsers, without ES2015 class support
* he don't get mentions from this repo

You can try to get him on e.g. twitter (https://twitter.com/youyuxi) and politely ask for an attention.

**Comment by yyx990803** [comment]
As stated in README:

> (For non-ES2015 support) You might want to reconsider since you'll be better off not using Web Components in this case.

So it's correct that I do not want to support non-ever green browsers (and all associated problems that come with it). You are welcome to fork it as a separate distribution though.

**Comment by egucciar** [comment]
we have a fork in use right now, but we're also strapped on resources and not able to really maintain our public repos during this timeframe. So feel free to take a look but be warned we will probably not be able to provide assistance , help or anything like that.

https://github.com/Updater/vue-web-component-wrapper

**Comment by VelenAranha** [comment]
@ChristianMurphy  Is there any reason why docs still say mention that [_Web Component mode does not support IE11 and below?_](https://cli.vuejs.org/guide/build-targets.html#web-component)

**Comment by ChristianMurphy** [comment]
Yes, because this wasn't merged, and IE11 isn't supported out of the box.
See the other comment in this PR and in https://github.com/vuejs/vue-web-component-wrapper/issues/31 for alternatives and work arounds.

**Comment by wbern** [comment]
@VelenAranha @ChristianMurphy I think my fork is worth checking out, it has at least 1 critical fix for IE11. https://github.com/vuejs/vue-web-component-wrapper/issues/79

**Pull request closed without merging**
